import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { api } from '../lib/api.js'

vi.mock('../lib/api.js', () => ({ api: vi.fn() }))
vi.mock('../lib/exercises.js', () => ({ registerCustom: vi.fn() }))
vi.mock('../lib/demo.js', () => ({ DEMO: false, DEMO_SEEDED: 'test-demo' }))
vi.mock('../lib/mobile.js', () => ({ MOBILE: false, nativeLoad: vi.fn(), nativeSave: vi.fn(), syncReminder: vi.fn() }))

const user = { id: 'member', name: 'Member' }
const profile = (ids = ['old'], _ts = 1000) => ({ workouts: ids.map(id => ({ id })), routines: [], bodyweight: [], _ts })
const deferred = () => {
  let resolve, reject
  const promise = new Promise((yes, no) => { resolve = yes; reject = no })
  return { promise, resolve, reject }
}
const puts = () => api.mock.calls.filter(([, options]) => options?.method === 'PUT').map(([, options]) => JSON.parse(options.body))

beforeEach(() => {
  vi.resetModules()
  vi.useFakeTimers()
  vi.setSystemTime(new Date('2026-10-05T12:00:00Z'))
  api.mockReset()
  const values = new Map()
  vi.stubGlobal('localStorage', {
    get length() { return values.size },
    key: i => [...values.keys()][i] ?? null,
    getItem: key => values.get(key) ?? null,
    setItem: (key, value) => values.set(key, String(value)),
    removeItem: key => values.delete(key),
  })
  vi.stubGlobal('document', new EventTarget())
  vi.stubGlobal('window', new EventTarget())
})
afterEach(() => { vi.clearAllTimers(); vi.useRealTimers(); vi.unstubAllGlobals() })

async function load({ signedIn = true, state = profile(), dirty = false, known = true, revision = 'base' } = {}) {
  localStorage.setItem('gym_state_v1', JSON.stringify(state))
  localStorage.setItem('gym_state_owner', signedIn ? user.id : 'guest')
  if (signedIn) localStorage.setItem('gym_user', JSON.stringify(user))
  if (dirty) localStorage.setItem('gym_dirty', '1')
  localStorage.setItem('gym_sync_v1', JSON.stringify({ owner: signedIn ? user.id : 'guest', known, revision }))
  const { useStore } = await import('./useStore.js')
  return useStore
}

describe('safe sign-out', () => {
  for (const action of ['signOut', 'signOutAll']) {
    it(`${action} keeps unsynced history and the account when the save fails offline`, async () => {
      const store = await load({ state: profile(['old', 'offline']), dirty: true })
      api.mockRejectedValue(new Error('offline'))
      await expect(store.getState()[action]()).rejects.toThrow('still signed in')
      expect(store.getState().user).toEqual(user)
      expect(store.getState().S.workouts.map(w => w.id)).toEqual(['old', 'offline'])
      expect(JSON.parse(localStorage.getItem('gym_state_v1')).workouts).toHaveLength(2)
      expect(localStorage.getItem('gym_dirty')).toBe('1')
      expect(api).toHaveBeenCalledTimes(1)
      expect(api.mock.calls[0][0]).toBe('/api/data')
    })
    it(`${action} clears the session only after a confirmed save and logout`, async () => {
      const store = await load({ dirty: true })
      localStorage.setItem('gym_saved_profile:member', JSON.stringify({ state: profile(), dirty: true }))
      api.mockImplementation(async (path, options) => options?.method === 'PUT' ? { revision: 'saved' } : { ok: true })
      await store.getState()[action]()
      expect(store.getState().user).toBeNull()
      expect(store.getState().S.workouts).toEqual([])
      expect(localStorage.getItem('gym_dirty')).toBeNull()
      expect(localStorage.getItem('gym_saved_profile:member')).toBeNull()
      expect(api.mock.calls[1][0]).toBe(action === 'signOut' ? '/api/logout' : '/api/logout/all')
    })
  }
  it('a logout failure preserves even an already-synced local profile', async () => {
    const store = await load()
    api.mockRejectedValue(new Error('logout failed'))
    await expect(store.getState().signOut()).rejects.toThrow('logout failed')
    expect(store.getState().user).toEqual(user)
    expect(store.getState().S.workouts).toHaveLength(1)
  })
  it('an active workout must be finished or explicitly discarded, never lost on sign-out', async () => {
    const store = await load({ state: { ...profile(), active: { id: 'unfinished', entries: [] } } })
    for (const action of ['signOut', 'signOutAll']) await expect(store.getState()[action]()).rejects.toThrow('active workout')
    expect(store.getState().S.active.id).toBe('unfinished')
    expect(store.getState().user).toEqual(user)
    expect(api).not.toHaveBeenCalled()
  })
  it('a late logout response cannot clear another profile after an account switch', async () => {
    const store = await load(), request = deferred()
    api.mockReturnValue(request.promise)
    const pending = store.getState().signOut()
    await vi.waitFor(() => expect(api).toHaveBeenCalled())
    const other = { id: 'other', name: 'Other' }
    store.getState().setUser(other)
    store.getState().update(s => s.workouts.push({ id: 'other-unsynced' }))
    request.resolve({ ok: true })
    await expect(pending).rejects.toThrow('profile changed')
    expect(store.getState().user).toEqual(other)
    expect(store.getState().S.workouts[0].id).toBe('other-unsynced')
    expect(localStorage.getItem('gym_dirty')).toBe('1')
  })
  it('edits made while logout is in flight are kept for signing back in', async () => {
    const store = await load(), pending = deferred()
    api.mockReturnValue(pending.promise)
    const logout = store.getState().signOut()
    await vi.waitFor(() => expect(api).toHaveBeenCalled())
    store.getState().update(s => s.workouts.push({ id: 'during-logout' }))
    pending.resolve({ ok: true })
    await expect(logout).rejects.toThrow('New changes were kept')
    expect(store.getState().S.workouts.map(w => w.id)).toEqual(['old', 'during-logout'])
    expect(localStorage.getItem('gym_dirty')).toBe('1')
    expect(store.getState().user).toBeNull()
  })
})

describe('guest and profile isolation', () => {
  it('restores guest workouts after a successful account sign-out without mixing profiles', async () => {
    const store = await load({ signedIn: false, state: profile(['guest-session']) })
    api.mockResolvedValue({ state: profile(['cloud-session']), revision: 'cloud' })
    store.getState().setUser(user)
    await store.getState().pullState()
    api.mockResolvedValue({ ok: true })
    await store.getState().signOut()
    store.getState().setGuest(true)
    expect(store.getState().S.workouts.map(w => w.id)).toEqual(['guest-session'])
    store.getState().update(s => s.workouts.push({ id: 'new-guest-session' }))
    store.getState().setGuest(true)
    expect(store.getState().S.workouts.map(w => w.id)).toEqual(['guest-session', 'new-guest-session'])
    expect(puts()).toEqual([])
    expect(localStorage.getItem('gym_saved_profile:member')).toBeNull()
  })
  it('existing-account sign-in loads cloud history without uploading guest history', async () => {
    const store = await load({ signedIn: false, state: profile(['guest-session'], 9000) })
    api.mockResolvedValue({ state: profile(['cloud-session'], 2000), revision: 'cloud' })
    store.getState().setUser(user)
    expect(store.getState().S.workouts).toEqual([])
    expect(await store.getState().pullState()).toBe(true)
    expect(store.getState().S.workouts.map(w => w.id)).toEqual(['cloud-session'])
    expect(puts()).toEqual([])
    expect(store.getState().recoveryCopies[0].state.workouts[0].id).toBe('guest-session')
    store.getState().setGuest(true)
    expect(store.getState().user).toBeNull()
    expect(store.getState().S.workouts[0].id).toBe('guest-session')
    expect(store.getState().syncStatus).toBe('idle')
  })
  it('explicit registration moves guest data only into the new, empty profile', async () => {
    const store = await load({ signedIn: false, state: profile(['guest-session']) })
    store.getState().setUser(user, { adoptLocal: true })
    api.mockResolvedValue({ revision: 'registered' })
    expect(await store.getState().pushState()).toBe(true)
    expect(puts()).toHaveLength(1)
    expect(puts()[0]).toMatchObject({ userId: user.id, baseRevision: null, state: { workouts: [{ id: 'guest-session' }] } })
    expect(store.getState().recoveryCopies[0].state.workouts[0].id).toBe('guest-session')
  })
  it('pending copies and their base revision stay tied to their profile on a switch', async () => {
    const store = await load({ dirty: true, state: profile(['member-unsynced']) })
    const other = { id: 'other', name: 'Other' }
    store.getState().setUser(other)
    expect(store.getState().S.workouts).toEqual([])
    expect(localStorage.getItem('gym_dirty')).toBeNull()
    store.getState().setUser(user)
    expect(store.getState().S.workouts[0].id).toBe('member-unsynced')
    expect(localStorage.getItem('gym_dirty')).toBe('1')
    expect(JSON.parse(localStorage.getItem('gym_sync_v1')).revision).toBe('base')
  })
  it('a late upload response cannot acknowledge or change the newly signed-in profile', async () => {
    const store = await load({ dirty: true }), upload = deferred()
    api.mockReturnValue(upload.promise)
    const pending = store.getState().pushState()
    store.getState().setUser({ id: 'other', name: 'Other' })
    store.getState().update(s => s.workouts.push({ id: 'other-only' }))
    upload.resolve({ revision: 'old-account-save' })
    expect(await pending).toBe(false)
    expect(localStorage.getItem('gym_dirty')).toBe('1')
    expect(store.getState().S.workouts[0].id).toBe('other-only')
    expect(JSON.parse(localStorage.getItem('gym_sync_v1')).revision).toBeNull()
  })
  it('does not switch profiles or clear data when recovery storage is full', async () => {
    const store = await load({ signedIn: false, state: profile(['guest-session']) })
    const original = localStorage.setItem
    localStorage.setItem = (key, value) => {
      if (key.startsWith('gym_recovery:')) throw new Error('Storage full')
      original(key, value)
    }
    expect(() => store.getState().setUser(user)).toThrow('Browser storage could not save')
    expect(store.getState().user).toBeNull()
    expect(store.getState().S.workouts[0].id).toBe('guest-session')
  })
})

describe('multiple browser tabs', () => {
  const anotherTab = async () => { vi.resetModules(); return (await import('./useStore.js')).useStore }
  it('an account switch in another tab cannot mislabel or overwrite the old profile’s edits', async () => {
    const a = await load(), b = await anotherTab(), other = { id: 'other', name: 'Other' }
    b.getState().setUser(other)
    b.getState().update(s => s.workouts.push({ id: 'other-private' }))
    a.getState().update(s => s.workouts.push({ id: 'member-pending' }))
    expect(await a.getState().pullState()).toBe(false)
    expect(await a.getState().pushState()).toBe(false)
    expect(api).not.toHaveBeenCalled()
    expect(localStorage.getItem('gym_state_owner')).toBe(other.id)
    expect(JSON.parse(localStorage.getItem('gym_state_v1')).workouts[0].id).toBe('other-private')
    expect(a.getState().S.workouts.some(w => w.id === 'member-pending')).toBe(true)
  })
  it('a stale tab saves the latest pending workout, never clears another tab’s unsent edit', async () => {
    const a = await load(), b = await anotherTab()
    a.getState().update(s => s.workouts.push({ id: 'unsynced-A' }))
    api.mockResolvedValue({ revision: 'saved' })
    expect(await b.getState().pushState()).toBe(true)
    expect(puts()[0].state.workouts.map(w => w.id)).toEqual(['old', 'unsynced-A'])
    expect(await a.getState().pushState()).toBe(true)
    expect(puts()).toHaveLength(1)
    const reloaded = await anotherTab()
    api.mockResolvedValue({ state: puts()[0].state, revision: 'saved' })
    expect(await reloaded.getState().pullState()).toBe(true)
    expect(reloaded.getState().S.workouts.map(w => w.id)).toEqual(['old', 'unsynced-A'])
  })
  it('a clean tab pulls pending device changes before reading the older cloud copy', async () => {
    const a = await load(), b = await anotherTab()
    a.getState().update(s => s.workouts.push({ id: 'new-A' }))
    api.mockImplementation(async (path, options) => options?.method === 'PUT' ? { revision: 'saved' } : { state: profile(), revision: 'base' })
    expect(await b.getState().pullState()).toBe(true)
    expect(b.getState().S.workouts.map(w => w.id)).toEqual(['old', 'new-A'])
    expect(puts()[0].state.workouts.map(w => w.id)).toEqual(['old', 'new-A'])
  })
  it('saving an identical closed-tab copy retires its journal without future false conflicts', async () => {
    const a = await load(), b = await anotherTab()
    a.getState().update(s => s.workouts.push({ id: 'saved-A' }))
    api.mockResolvedValue({ revision: 'saved-A' })
    expect(await b.getState().pushState()).toBe(true)
    b.getState().update(s => { s.unit = 'lb' })
    api.mockResolvedValue({ revision: 'saved-B' })
    expect(await b.getState().pushState()).toBe(true)
    const reloaded = await anotherTab()
    expect(reloaded.getState().syncStatus).not.toBe('conflict')
    expect(reloaded.getState().S.workouts.map(w => w.id)).toEqual(['old', 'saved-A'])
    expect(reloaded.getState().S.unit).toBe('lb')
  })
  it('a new edit in a clean tab is based on the newest device snapshot', async () => {
    const a = await load(), b = await anotherTab()
    a.getState().update(s => s.workouts.push({ id: 'A' }))
    b.getState().update(s => s.workouts.push({ id: 'B' }))
    expect(b.getState().S.workouts.map(w => w.id)).toEqual(['old', 'A', 'B'])
    expect(JSON.parse(localStorage.getItem('gym_state_v1')).workouts.map(w => w.id)).toEqual(['old', 'A', 'B'])
  })
  it('a late acknowledgment cannot clear an edit made by another tab during upload', async () => {
    const a = await load({ dirty: true }), b = await anotherTab(), upload = deferred()
    api.mockReturnValue(upload.promise)
    const saving = a.getState().pushState()
    b.getState().update(s => s.workouts.push({ id: 'B-during-upload' }))
    upload.resolve({ revision: 'first-save' })
    expect(await saving).toBe(false)
    expect(a.getState().syncStatus).toBe('conflict')
    expect(localStorage.getItem('gym_dirty')).toBe('1')
    expect(JSON.parse(localStorage.getItem('gym_state_v1')).workouts.map(w => w.id)).toEqual(['old', 'B-during-upload'])
    expect(JSON.parse(localStorage.getItem('gym_sync_v1')).revision).toBe('base')
  })
  it('divergent tab edits remain durable without replacing the other tab’s copy', async () => {
    const a = await load(), b = await anotherTab()
    a.getState().update(s => s.workouts.push({ id: 'A' }))
    b.getState().update(s => s.workouts.push({ id: 'B' }))
    a.getState().update(s => s.workouts.push({ id: 'A-unpublished' }))
    expect(a.getState().syncStatus).toBe('conflict')
    expect(JSON.parse(localStorage.getItem('gym_state_v1')).workouts.map(w => w.id)).toEqual(['old', 'A', 'B'])
    const reloaded = await anotherTab()
    expect(reloaded.getState().syncStatus).toBe('conflict')
    expect(await reloaded.getState().pullState()).toBe(false)
    expect(reloaded.getState().recoveryCopies.some(copy => copy.state.workouts.some(w => w.id === 'A-unpublished'))).toBe(true)
    expect(api).not.toHaveBeenCalled()
  })
})

describe('reset and backup replacement', () => {
  it('reset uses one versioned save to remove history and Coach consent', async () => {
    const store = await load({ state: { ...profile(), coach: { consent: { version: 1, agreedAt: '2026-10-05T10:00:00Z' } } } })
    api.mockResolvedValue({ revision: 'reset' })
    await store.getState().resetAll()
    expect(puts()).toHaveLength(1)
    expect(puts()[0]).toMatchObject({ baseRevision: 'base', state: { workouts: [], coach: null } })
    expect(api.mock.calls.some(([path]) => path === '/api/coach/forget')).toBe(false)
    expect(store.getState().recoveryCopies[0].state.workouts[0].id).toBe('old')
    expect(store.getState().syncStatus).toBe('synced')
  })
  it('an offline reset stays pending and preserves a recoverable original', async () => {
    const store = await load()
    api.mockRejectedValue(new Error('offline'))
    await expect(store.getState().resetAll()).rejects.toThrow('cloud sync still needs attention')
    expect(store.getState().S.workouts).toEqual([])
    expect(localStorage.getItem('gym_dirty')).toBe('1')
    expect(store.getState().recoveryCopies[0].state.workouts[0].id).toBe('old')
  })
  it('a backup replacement archives the current device data first', async () => {
    const store = await load()
    store.getState().importBackup(profile(['imported']))
    expect(store.getState().S.workouts[0].id).toBe('imported')
    expect(store.getState().recoveryCopies[0].state.workouts[0].id).toBe('old')
    expect(localStorage.getItem('gym_dirty')).toBe('1')
  })
  it('storage-full cannot erase the device copy during reset or backup replacement', async () => {
    const store = await load(), original = localStorage.setItem
    localStorage.setItem = (key, value) => { if (key.startsWith('gym_recovery:')) throw new Error('Storage full'); original(key, value) }
    expect(() => store.getState().importBackup(profile(['imported']))).toThrow('Storage full')
    await expect(store.getState().resetAll()).rejects.toThrow('Storage full')
    expect(store.getState().S.workouts[0].id).toBe('old')
    expect(api).not.toHaveBeenCalled()
  })
})

describe('versioned, serialized sync', () => {
  it('marks edits pending immediately, before the debounce can be interrupted', async () => {
    const store = await load()
    store.getState().update(s => s.workouts.push({ id: 'new' }))
    expect(localStorage.getItem('gym_dirty')).toBe('1')
    expect(store.getState().syncStatus).toBe('pending')
    expect(api).not.toHaveBeenCalled()
  })
  it('imported non-numeric timestamps cannot break edit versions or upload acknowledgments', async () => {
    const store = await load({ state: profile(['old'], 'invalid-imported-time') })
    store.getState().update(s => { s.unit = 'lb' })
    api.mockResolvedValue({ revision: 'saved' })
    expect(Number.isFinite(store.getState().S._ts)).toBe(true)
    expect(await store.getState().pushState()).toBe(true)
    expect(localStorage.getItem('gym_dirty')).toBeNull()
  })
  it('never retries a rejected stale save blindly or clears its dirty flag', async () => {
    const store = await load({ dirty: true })
    api.mockRejectedValue(Object.assign(new Error('conflict'), { status: 409 }))
    expect(await store.getState().pushState()).toBe(false)
    expect(store.getState().syncStatus).toBe('conflict')
    expect(localStorage.getItem('gym_dirty')).toBe('1')
    expect(await store.getState().pushState()).toBe(false)
    expect(api).toHaveBeenCalledTimes(1)
    expect(store.getState().S.workouts).toHaveLength(1)
  })
  it('cloud pull keeps pending edits when a different device changed the base', async () => {
    const store = await load({ dirty: true, state: profile(['local-only']) })
    api.mockResolvedValue({ state: profile(['remote-only']), revision: 'different' })
    expect(await store.getState().pullState()).toBe(false)
    expect(store.getState().S.workouts[0].id).toBe('local-only')
    expect(store.getState().syncStatus).toBe('conflict')
    expect(puts()).toEqual([])
  })
  it('a matching base allows reconnect sync without replacing the device copy first', async () => {
    const store = await load({ dirty: true, state: profile(['local-only']) })
    api.mockImplementation(async (path, opts) => opts?.method === 'PUT' ? { revision: 'saved' } : { state: profile(), revision: 'base' })
    expect(await store.getState().pullState()).toBe(true)
    expect(puts()[0].state.workouts[0].id).toBe('local-only')
    expect(localStorage.getItem('gym_dirty')).toBeNull()
  })
  it('keeps newer legacy data rather than treating the device clock as overwrite permission', async () => {
    const store = await load({ known: false, state: profile(['legacy-only'], 9000) })
    api.mockResolvedValue({ state: profile(['cloud'], 2000), revision: 'cloud' })
    expect(await store.getState().pullState()).toBe(false)
    expect(store.getState().S.workouts[0].id).toBe('legacy-only')
    expect(store.getState().syncStatus).toBe('conflict')
  })
  it('an old backend without revisions cannot receive an unsafe save', async () => {
    const store = await load({ known: false, dirty: true })
    api.mockResolvedValue({ state: null })
    expect(await store.getState().pushState()).toBe(false)
    expect(store.getState().syncError).toContain('server together')
    expect(puts()).toEqual([])
    expect(localStorage.getItem('gym_dirty')).toBe('1')
  })
  it('edits during an upload get a second serialized save with the acknowledged revision', async () => {
    const store = await load({ dirty: true }), first = deferred()
    api.mockReturnValueOnce(first.promise).mockResolvedValue({ revision: 'second' })
    const pending = store.getState().pushState()
    store.getState().update(s => s.workouts.push({ id: 'during-upload' }))
    const another = store.getState().pushState()
    expect(puts()).toHaveLength(1)
    first.resolve({ revision: 'first' })
    expect(await pending).toBe(true)
    expect(await another).toBe(true)
    expect(puts()).toHaveLength(2)
    expect(puts()[1].baseRevision).toBe('first')
    expect(puts()[1].state.workouts.map(w => w.id)).toEqual(['old', 'during-upload'])
    expect(localStorage.getItem('gym_dirty')).toBeNull()
  })
  it('a failed second save does not let the first acknowledgment clear new pending edits', async () => {
    const store = await load({ dirty: true }), first = deferred()
    api.mockReturnValueOnce(first.promise).mockRejectedValue(new Error('offline'))
    const pending = store.getState().pushState()
    store.getState().update(s => s.workouts.push({ id: 'not-yet-saved' }))
    first.resolve({ revision: 'first' })
    expect(await pending).toBe(false)
    expect(localStorage.getItem('gym_dirty')).toBe('1')
    expect(store.getState().S.workouts).toHaveLength(2)
    expect(JSON.parse(localStorage.getItem('gym_sync_v1')).revision).toBe('first')
  })
  it('retries an offline save when the browser comes online', async () => {
    const store = await load({ dirty: true })
    api.mockRejectedValueOnce(new Error('offline')).mockResolvedValue({ revision: 'saved' })
    expect(await store.getState().pushState()).toBe(false)
    window.dispatchEvent(new Event('online'))
    await vi.waitFor(() => expect(store.getState().syncStatus).toBe('synced'))
    expect(localStorage.getItem('gym_dirty')).toBeNull()
  })
  it('an old pull response cannot undo a save that completed while it was being fetched', async () => {
    const store = await load(), read = deferred()
    api.mockReturnValueOnce(read.promise).mockResolvedValueOnce({ revision: 'saved' })
      .mockResolvedValue({ state: profile(['old', 'new'], 9000), revision: 'saved' })
    const pulling = store.getState().pullState()
    store.getState().update(s => s.workouts.push({ id: 'new' }))
    expect(await store.getState().pushState()).toBe(true)
    read.resolve({ state: profile(['old']), revision: 'base' })
    expect(await pulling).toBe(true)
    expect(store.getState().S.workouts.map(w => w.id)).toEqual(['old', 'new'])
  })
  it('cloud pulls preserve server timestamps and the local active workout', async () => {
    const store = await load({ state: { ...profile(), active: { id: 'in-progress', entries: [] } } })
    api.mockResolvedValue({ state: profile(['cloud'], 555), revision: 'cloud' })
    expect(await store.getState().pullState()).toBe(true)
    expect(store.getState().S._ts).toBe(555)
    expect(store.getState().S.active.id).toBe('in-progress')
    expect(localStorage.getItem('gym_dirty')).toBeNull()
  })
})

describe('browser storage failures', () => {
  const quota = () => Object.assign(new Error('Storage full'), { name: 'QuotaExceededError' })
  const failWrites = predicate => {
    const original = localStorage.setItem
    localStorage.setItem = (key, value) => { if (predicate(key)) throw quota(); original(key, value) }
    return () => { localStorage.setItem = original }
  }
  for (const failedKey of ['gym_device_profile:other', 'gym_state_owner', 'gym_user']) {
    it(`does not mix accounts when switching fails at ${failedKey}, including after retry and reload`, async () => {
      const store = await load({ dirty: true, state: profile(['member-private']) })
      const other = { id: 'other', name: 'Other' }
      const before = store.getState().S
      const restore = failWrites(key => key === failedKey)
      expect(() => store.getState().setUser(other)).toThrow('Browser storage could not save')
      expect(store.getState().user).toEqual(user)
      expect(store.getState().S).toBe(before)
      expect(store.getState().profileLoading).toBe(false)
      expect(localStorage.getItem('gym_state_owner')).toBe(user.id)
      expect(JSON.parse(localStorage.getItem('gym_user'))).toEqual(user)
      expect(JSON.parse(localStorage.getItem('gym_sync_v1')).owner).toBe(user.id)
      expect(localStorage.getItem('gym_dirty')).toBe('1')
      expect(localStorage.getItem('gym_device_profile:other')).toBeNull()
      expect(store.getState().storageError).toBeTruthy()
      restore()
      vi.resetModules()
      const reloaded = (await import('./useStore.js')).useStore
      expect(reloaded.getState().user).toEqual(user)
      expect(reloaded.getState().S.workouts.map(w => w.id)).toEqual(['member-private'])
      store.getState().setUser(other)
      expect(store.getState().user).toEqual(other)
      expect(store.getState().profileLoading).toBe(true)
      expect(store.getState().S.workouts).toEqual([])
      expect(JSON.parse(localStorage.getItem('gym_device_profile:other')).state.workouts).toEqual([])
      expect(store.getState().storageError).toBe('')
      api.mockResolvedValue({ state: profile(['other-private']), revision: 'other-base' })
      expect(await store.getState().pullState()).toBe(true)
      store.getState().update(s => s.workouts.push({ id: 'other-new' }))
      api.mockResolvedValue({ revision: 'other-saved' })
      expect(await store.getState().pushState()).toBe(true)
      expect(puts()[0]).toMatchObject({ userId: other.id, state: { workouts: [{ id: 'other-private' }, { id: 'other-new' }] } })
    })
  }
  it('rolls back registration adoption and preserves the guest flag when storing the login fails', async () => {
    const store = await load({ signedIn: false, state: profile(['guest-private']) })
    localStorage.setItem('gym_guest', '1')
    const restore = failWrites(key => key === 'gym_user')
    expect(() => store.getState().setUser(user, { adoptLocal: true })).toThrow('Browser storage could not save')
    expect(store.getState().user).toBeNull()
    expect(store.getState().S.workouts[0].id).toBe('guest-private')
    expect(localStorage.getItem('gym_state_owner')).toBe('guest')
    expect(localStorage.getItem('gym_guest')).toBe('1')
    expect(localStorage.getItem('gym_device_profile:member')).toBeNull()
    expect(Array.from({ length: localStorage.length }, (_, i) => localStorage.key(i))
      .filter(key => key.startsWith('gym_pending_profile:member:'))).toEqual([])
    restore()
    store.getState().setUser(user, { adoptLocal: true })
    expect(store.getState().S.workouts[0].id).toBe('guest-private')
    expect(store.getState().profileLoading).toBe(false)
    api.mockResolvedValue({ revision: 'adopted' })
    expect(await store.getState().pushState()).toBe(true)
    expect(puts()[0]).toMatchObject({ userId: user.id, baseRevision: null })
  })
  it('restores an existing destination cache and journal when a late login write fails', async () => {
    const store = await load({ dirty: true })
    const cached = JSON.stringify({ state: profile(['other-saved']), meta: { owner: 'other', known: true, revision: 'other-base' }, dirty: true })
    localStorage.setItem('gym_device_profile:other', cached)
    const restore = failWrites(key => key === 'gym_user')
    expect(() => store.getState().setUser({ id: 'other' })).toThrow('Browser storage could not save')
    expect(localStorage.getItem('gym_device_profile:other')).toBe(cached)
    expect(store.getState().S.workouts[0].id).toBe('old')
    restore()
    store.getState().setUser({ id: 'other' })
    expect(store.getState().S.workouts[0].id).toBe('other-saved')
    expect(JSON.parse(localStorage.getItem('gym_sync_v1')).revision).toBe('other-base')
  })
  for (const failedKey of ['gym_device_profile:guest', 'gym_guest']) {
    it(`keeps the signed-in profile when guest switching fails at ${failedKey}`, async () => {
      const store = await load({ dirty: true })
      localStorage.setItem('gym_saved_profile:guest', JSON.stringify({ state: profile(['guest-private']) }))
      const before = store.getState().S
      const restore = failWrites(key => key === failedKey)
      expect(() => store.getState().setGuest(true)).toThrow('Browser storage could not save')
      expect(store.getState().user).toEqual(user)
      expect(store.getState().S).toBe(before)
      expect(localStorage.getItem('gym_state_owner')).toBe(user.id)
      expect(JSON.parse(localStorage.getItem('gym_user'))).toEqual(user)
      expect(localStorage.getItem('gym_guest')).toBeNull()
      expect(localStorage.getItem('gym_dirty')).toBe('1')
      restore()
      store.getState().setGuest(true)
      expect(store.getState().user).toBeNull()
      expect(store.getState().S.workouts[0].id).toBe('guest-private')
      expect(localStorage.getItem('gym_state_owner')).toBe('guest')
      expect(localStorage.getItem('gym_guest')).toBe('1')
    })
  }
  it('does not clear the old profile before guest restoration succeeds on sign-out', async () => {
    const store = await load()
    localStorage.setItem('gym_saved_profile:guest', JSON.stringify({ state: profile(['guest-private']) }))
    api.mockResolvedValue({ ok: true })
    const before = store.getState().S
    const restore = failWrites(key => key === 'gym_device_profile:guest')
    await expect(store.getState().signOut()).rejects.toThrow('Browser storage could not save')
    expect(store.getState().user).toEqual(user)
    expect(store.getState().S).toBe(before)
    expect(localStorage.getItem('gym_state_owner')).toBe(user.id)
    expect(JSON.parse(localStorage.getItem('gym_user'))).toEqual(user)
    expect(JSON.parse(localStorage.getItem('gym_device_profile:member')).state.workouts[0].id).toBe('old')
    restore()
    await store.getState().signOut()
    expect(store.getState().user).toBeNull()
    expect(store.getState().S.workouts[0].id).toBe('guest-private')
    expect(localStorage.getItem('gym_state_owner')).toBe('guest')
    expect(localStorage.getItem('gym_device_profile:member')).toBeNull()
  })
  for (const savedCopy of [false, true]) {
    it(`never reloads a mismatched account mirror${savedCopy ? ' and restores the matching saved copy' : ''}`, async () => {
      const store = await load()
      localStorage.setItem('gym_state_owner', 'other')
      localStorage.setItem('gym_state_v1', JSON.stringify(profile(['other-private'])))
      localStorage.setItem('gym_sync_v1', JSON.stringify({ owner: 'other', known: true, revision: 'other-base' }))
      localStorage.setItem('gym_dirty', '1')
      if (savedCopy) localStorage.setItem('gym_saved_profile:member', JSON.stringify({ state: store.getState().S,
        meta: { owner: user.id, known: true, revision: 'base' }, dirty: true }))
      vi.resetModules()
      const reloaded = (await import('./useStore.js')).useStore
      expect(reloaded.getState().user).toEqual(user)
      expect(reloaded.getState().S.workouts.map(w => w.id)).toEqual(savedCopy ? ['old'] : [])
      expect(reloaded.getState().syncStatus).toBe(savedCopy ? 'pending' : 'idle')
      expect(reloaded.getState().update(s => { s.restSec = 60 })).toBe(true)
      expect(localStorage.getItem('gym_state_owner')).toBe(user.id)
      expect(JSON.parse(localStorage.getItem('gym_device_profile:member')).meta.owner).toBe(user.id)
    })
  }
  it('rejects a new workout before publishing it when the pending journal is full', async () => {
    const store = await load()
    expect(await store.getState().pushState()).toBe(true)
    failWrites(key => key.startsWith('gym_pending_profile:'))
    expect(store.getState().update(s => s.workouts.push({ id: 'not-saved' }))).toBe(false)
    expect(store.getState().S.workouts.map(w => w.id)).toEqual(['old'])
    expect(store.getState().syncStatus).toBe('error')
    expect(store.getState().storageError).toContain('retry the change')
    vi.resetModules()
    const reloaded = (await import('./useStore.js')).useStore
    expect(reloaded.getState().S.workouts.map(w => w.id)).toEqual(['old'])
    await vi.advanceTimersByTimeAsync(1500)
    expect(api).not.toHaveBeenCalled()
  })
  it('keeps a guest’s active workout when the atomic device write is rejected', async () => {
    const state = { ...profile(), active: { id: 'current', entries: [{ id: 'plank', sets: [{ done: true }] }] } }
    const store = await load({ signedIn: false, state })
    failWrites(key => key.startsWith('gym_device_profile:'))
    expect(store.getState().update(s => { s.workouts.push(s.active); s.active = null })).toBe(false)
    expect(store.getState().S.active.id).toBe('current')
    expect(store.getState().S.workouts).toHaveLength(1)
    expect(store.getState().storageError).toContain('last saved copy was kept')
    expect(JSON.parse(localStorage.getItem('gym_state_v1')).active.id).toBe('current')
  })
  it('restores the prior pending journal if publishing its replacement fails', async () => {
    const store = await load()
    store.getState().update(s => s.workouts.push({ id: 'pending' }))
    const restore = failWrites(key => key.startsWith('gym_device_profile:'))
    expect(store.getState().update(s => s.workouts.push({ id: 'rejected' }))).toBe(false)
    const keys = Array.from({ length: localStorage.length }, (_, i) => localStorage.key(i)).filter(key => key.startsWith('gym_pending_profile:'))
    expect(keys).toHaveLength(1)
    expect(JSON.parse(localStorage.getItem(keys[0])).state.workouts.map(w => w.id)).toEqual(['old', 'pending'])
    restore()
    expect(store.getState().update(s => s.workouts.push({ id: 'retried' }))).toBe(true)
    expect(store.getState().storageError).toBe('')
    api.mockResolvedValue({ revision: 'saved' })
    expect(await store.getState().pushState()).toBe(true)
    expect(puts()[0].state.workouts.map(w => w.id)).toEqual(['old', 'pending', 'retried'])
  })
  it('a quota failure during a sync error stays visible and returns false without rejecting', async () => {
    const store = await load()
    store.getState().update(s => s.workouts.push({ id: 'durable-pending' }))
    failWrites(() => true)
    await expect(store.getState().pushState()).resolves.toBe(false)
    expect(store.getState().storageError).toBeTruthy()
    expect(store.getState().S.workouts).toHaveLength(2)
    expect(api).not.toHaveBeenCalled()
  })
  it('uses the atomic profile copy after a compatibility mirror fails at quota', async () => {
    const store = await load()
    failWrites(key => key === 'gym_state_v1' || key === 'gym_sync_v1' || key === 'gym_dirty')
    expect(store.getState().update(s => s.workouts.push({ id: 'durably-saved' }))).toBe(true)
    vi.resetModules()
    const reloaded = (await import('./useStore.js')).useStore
    expect(reloaded.getState().S.workouts.map(w => w.id)).toEqual(['old', 'durably-saved'])
    expect(reloaded.getState().syncStatus).toBe('pending')
    api.mockResolvedValue({ revision: 'saved' })
    expect(await reloaded.getState().pushState()).toBe(true)
    vi.resetModules()
    const final = (await import('./useStore.js')).useStore
    expect(final.getState().S.workouts).toHaveLength(2)
    expect(final.getState().syncStatus).not.toBe('pending')
  })
})

describe('authoritative consent corrections', () => {
  const consent = { version: 1, agreedAt: '2026-10-04T12:00:00Z' }
  const coach = () => ({ consent: { ...consent }, cadence: { everyWorkouts: 4 }, profile: { goal: 'strength' }, log: [{ id: 'history' }] })
  it('reflects server-revoked backup consent immediately and keeps history and an active workout', async () => {
    const store = await load({ dirty: true, state: { ...profile(), coach: coach(), active: { id: 'current' } } })
    api.mockResolvedValue({ revision: 'normalized', coachConsentCleared: true })
    expect(await store.getState().pushState()).toBe(true)
    expect(store.getState().S.coach).toMatchObject({ consent: null, cadence: 'off', profile: { goal: 'strength' }, log: [{ id: 'history' }] })
    expect(store.getState().S.active.id).toBe('current')
    expect(store.getState().S.workouts).toHaveLength(1)
    expect(store.getState().syncStatus).toBe('synced')
    vi.resetModules()
    const reloaded = (await import('./useStore.js')).useStore
    expect(reloaded.getState().S.coach.consent).toBeNull()
    expect(reloaded.getState().syncStatus).not.toBe('conflict')
  })
  it('corrects stale consent without overwriting unrelated edits made during the upload', async () => {
    const store = await load({ dirty: true, state: { ...profile(), coach: coach() } }), first = deferred()
    api.mockReturnValueOnce(first.promise).mockResolvedValue({ revision: 'latest', coachConsentCleared: true })
    const saving = store.getState().pushState()
    store.getState().update(s => { s.workouts.push({ id: 'during-upload' }); s.coach.profile.goal = 'muscle' })
    first.resolve({ revision: 'normalized', coachConsentCleared: true })
    expect(await saving).toBe(true)
    expect(puts()).toHaveLength(2)
    expect(puts()[1]).toMatchObject({ baseRevision: 'normalized', state: { coach: { consent: null, profile: { goal: 'muscle' } }, workouts: [{ id: 'old' }, { id: 'during-upload' }] } })
    expect(store.getState().S.workouts).toHaveLength(2)
  })
  it('never revokes a newer explicit acceptance because an older upload was normalized', async () => {
    const store = await load({ dirty: true, state: { ...profile(), coach: coach() } }), first = deferred()
    api.mockReturnValueOnce(first.promise).mockResolvedValue({ revision: 'latest' })
    const saving = store.getState().pushState(), fresh = { version: 1, agreedAt: '2026-10-05T12:00:00Z' }
    store.getState().update(s => { s.coach.consent = fresh })
    first.resolve({ revision: 'normalized', coachConsentCleared: true })
    expect(await saving).toBe(true)
    expect(puts()[1].state.coach.consent).toEqual(fresh)
    expect(store.getState().S.coach.consent).toEqual(fresh)
  })
})

describe('explicit conflict recovery', () => {
  it('using cloud data archives the unsynced device copy before replacing history', async () => {
    const store = await load({ dirty: true, state: { ...profile(['local-only']), active: { id: 'active' } } })
    api.mockResolvedValue({ state: profile(['remote-only']), revision: 'remote' })
    expect(await store.getState().resolveSyncConflict('cloud')).toBe(true)
    expect(store.getState().S.workouts[0].id).toBe('remote-only')
    expect(store.getState().S.active.id).toBe('active')
    expect(store.getState().recoveryCopies[0].state.workouts[0].id).toBe('local-only')
    expect(localStorage.getItem('gym_dirty')).toBeNull()
    expect(puts()).toEqual([])
  })
  it('using device data archives the cloud copy and still requires a matching fresh revision', async () => {
    const store = await load({ dirty: true, state: profile(['local-only']) })
    api.mockResolvedValueOnce({ state: profile(['remote-only']), revision: 'remote' }).mockResolvedValue({ revision: 'saved' })
    expect(await store.getState().resolveSyncConflict('local')).toBe(true)
    expect(store.getState().recoveryCopies[0].state.workouts[0].id).toBe('remote-only')
    expect(puts()[0].baseRevision).toBe('remote')
    expect(puts()[0].state.workouts[0].id).toBe('local-only')
  })
  it('a recovery export contains complete backup fields even for a minimal legacy cloud profile', async () => {
    const store = await load({ dirty: true })
    api.mockResolvedValueOnce({ state: { workouts: [{ id: 'legacy-cloud' }] }, revision: 'remote' }).mockResolvedValue({ revision: 'saved' })
    expect(await store.getState().resolveSyncConflict('local')).toBe(true)
    expect(store.getState().recoveryCopies[0].state.routines).toEqual([])
    expect(store.getState().recoveryCopies[0].state.workouts[0].id).toBe('legacy-cloud')
  })
  it('another concurrent cloud change during resolution is rejected without losing either copy', async () => {
    const store = await load({ dirty: true, state: profile(['local-only']) })
    api.mockResolvedValueOnce({ state: profile(['remote-only']), revision: 'remote' })
      .mockRejectedValue(Object.assign(new Error('changed again'), { status: 409 }))
    expect(await store.getState().resolveSyncConflict('local')).toBe(false)
    expect(store.getState().S.workouts[0].id).toBe('local-only')
    expect(store.getState().recoveryCopies[0].state.workouts[0].id).toBe('remote-only')
    expect(localStorage.getItem('gym_dirty')).toBe('1')
    expect(store.getState().syncStatus).toBe('conflict')
  })
})
